#!/usr/bin/env node
/**
 * Regenerates public/assets/tokens.css from the MCTL design system.
 *
 * The page used to carry a hand-written copy of the semantic token layer and
 * then load the design system over it from a CDN URL that carries no version.
 * Two problems: the copy drifted by hand, and the page could change without a
 * commit anywhere, because that URL always serves whatever is deployed.
 *
 * So the stylesheet is vendored here instead, byte for byte, and nothing is
 * fetched at runtime. `--check` in CI compares the committed file against the
 * source and fails on a difference, which turns what used to be a silent
 * change into a reviewable diff. With a pinned SOURCE that check can now only
 * fail because someone edited the vendored copy by hand or moved SOURCE — not
 * because the design system shipped something upstream.
 *
 * ## Why the pinned CDN path and not the package
 *
 * SOURCE points at a version, not at the floating `ui.mctl.ai/mctl.css`. That
 * path is served `immutable` for a year and mctl-design's CI refuses to edit,
 * move or delete an already-published version directory, so the bytes behind
 * it cannot change: upgrading is an edit made here on purpose rather than
 * something that happens to this page four hours after an unrelated merge on
 * another repository (mctlhq/mctl-design#75, #76).
 *
 * `@mctlhq/css@0.5.0` on GitHub Packages carries the same sheet and would also
 * be pinnable. It is not used because consuming it needs a GitHub Packages
 * token in this repository's CI and in the container build, which is
 * centralised in mctl-gitops and has no npm credentials. The pinned URL buys
 * the same immovability without distributing a credential.
 *
 * Until 2026-09-09 there was a sharper reason to avoid the package: the
 * published 0.4.0 predated the editorial-warm rebrand, so it was cyan on Geist
 * where the CDN served terracotta on Onest. mctl-design 0.5.0 closed that.
 */
import { readFileSync, writeFileSync } from "node:fs";

const SOURCE = "https://ui.mctl.ai/0.5.0/mctl.css";
const OUTPUT = new URL("../public/assets/tokens.css", import.meta.url).pathname;

/**
 * The one thing the design system does not provide: following the operating
 * system when the visitor has never chosen a theme. The package defines the
 * light surfaces only under an explicit [data-theme='light'].
 *
 * The block is derived from that rule rather than written out, so it can never
 * name a variable the pinned version does not define. That matters: the
 * published 0.4.0 has a different token vocabulary from the build the CDN
 * currently serves, and a hand-written block against the wrong one produces a
 * light theme of empty values.
 */
function systemPreferenceBlock(themeCss) {
  const match = themeCss.match(/\[data-theme=['"]light['"]\]\s*\{([^}]*)\}/);
  if (!match) {
    throw new Error("no [data-theme='light'] rule in theme.css — the package layout changed");
  }
  const declarations = match[1]
    .split(";")
    .map((line) => line.trim())
    .filter(Boolean)
    .map((line) => `    ${line};`)
    .join("\n");
  return `
/* ── seerrsense addition ─────────────────────────────────────────────────
   Derived from the package's own [data-theme='light'] rule by
   scripts/sync-tokens.mjs. A visitor who has never touched the toggle gets the
   light palette when their system asks for it; an explicit choice still wins,
   which is what :root:not([data-theme]) is for.
   ──────────────────────────────────────────────────────────────────────── */
@media (prefers-color-scheme: light) {
  :root:not([data-theme]) {
    color-scheme: light;
${declarations}
  }
}
`;
}

async function fetchThemeCss() {
  const response = await fetch(SOURCE, { redirect: "error" });
  if (!response.ok) throw new Error(`${SOURCE} returned ${response.status}`);
  return response.text();
}

function render(themeCss) {
  return [
    `/* Generated by scripts/sync-tokens.mjs from ${SOURCE}. Do not edit. */`,
    themeCss.trimEnd(),
    systemPreferenceBlock(themeCss).trimStart(),
  ].join("\n");
}

const wanted = render(await fetchThemeCss());

if (process.argv.includes("--check")) {
  const current = readFileSync(OUTPUT, "utf8");
  if (current !== wanted) {
    console.error(
      `public/assets/tokens.css no longer matches ${SOURCE}.\n` +
        "The design system changed. Run `npm run sync:tokens`, look at the diff, and commit it.",
    );
    process.exit(1);
  }
  console.log(`public/assets/tokens.css matches ${SOURCE}`);
} else {
  writeFileSync(OUTPUT, wanted);
  console.log(`wrote public/assets/tokens.css from ${SOURCE}`);
}
