#!/usr/bin/env node
/**
 * Regenerates public/assets/tokens.css from the MCTL design system.
 *
 * The page used to carry a hand-written copy of the semantic token layer and
 * then load the design system over it from a CDN URL that carries no version.
 * Two problems: the copy drifted by hand, and the page could change without a
 * commit anywhere, because that URL always serves whatever is deployed.
 *
 * So the stylesheet is vendored here instead, byte for byte, and nothing is
 * fetched at runtime. `--check` in CI compares the committed file against the
 * source and fails on a difference, which turns what used to be a silent
 * change into a reviewable diff.
 *
 * ## Why the CDN and not the package
 *
 * `@mctlhq/css` is published to GitHub Packages, and taking the tokens from a
 * pinned version there would be better: a version to point at, no reliance on
 * an unversioned URL. It cannot be done yet. The published 0.4.0 (2026-08-08)
 * is not merely older than what the CDN serves, it is a different visual
 * identity: its accent is cyan #00e5ff and its display font is Geist, where
 * the deployed sheet is terracotta #e25a3c and Onest. Vendoring the package
 * today would silently restyle the site.
 *
 * Switching over is a one-line change to SOURCE once mctl-design publishes a
 * version that matches what it deploys — mctlhq/mctl-design#75.
 */
import { readFileSync, writeFileSync } from "node:fs";

const SOURCE = "https://ui.mctl.ai/mctl.css";
const OUTPUT = new URL("../public/assets/tokens.css", import.meta.url).pathname;

/**
 * The one thing the design system does not provide: following the operating
 * system when the visitor has never chosen a theme. The package defines the
 * light surfaces only under an explicit [data-theme='light'].
 *
 * The block is derived from that rule rather than written out, so it can never
 * name a variable the pinned version does not define. That matters: the
 * published 0.4.0 has a different token vocabulary from the build the CDN
 * currently serves, and a hand-written block against the wrong one produces a
 * light theme of empty values.
 */
function systemPreferenceBlock(themeCss) {
  const match = themeCss.match(/\[data-theme=['"]light['"]\]\s*\{([^}]*)\}/);
  if (!match) {
    throw new Error("no [data-theme='light'] rule in theme.css — the package layout changed");
  }
  const declarations = match[1]
    .split(";")
    .map((line) => line.trim())
    .filter(Boolean)
    .map((line) => `    ${line};`)
    .join("\n");
  return `
/* ── seerrsense addition ─────────────────────────────────────────────────
   Derived from the package's own [data-theme='light'] rule by
   scripts/sync-tokens.mjs. A visitor who has never touched the toggle gets the
   light palette when their system asks for it; an explicit choice still wins,
   which is what :root:not([data-theme]) is for.
   ──────────────────────────────────────────────────────────────────────── */
@media (prefers-color-scheme: light) {
  :root:not([data-theme]) {
    color-scheme: light;
${declarations}
  }
}
`;
}

async function fetchThemeCss() {
  const response = await fetch(SOURCE, { redirect: "error" });
  if (!response.ok) throw new Error(`${SOURCE} returned ${response.status}`);
  return response.text();
}

function render(themeCss) {
  return [
    `/* Generated by scripts/sync-tokens.mjs from ${SOURCE}. Do not edit. */`,
    themeCss.trimEnd(),
    systemPreferenceBlock(themeCss).trimStart(),
  ].join("\n");
}

const wanted = render(await fetchThemeCss());

if (process.argv.includes("--check")) {
  const current = readFileSync(OUTPUT, "utf8");
  if (current !== wanted) {
    console.error(
      `public/assets/tokens.css no longer matches ${SOURCE}.\n` +
        "The design system changed. Run `npm run sync:tokens`, look at the diff, and commit it.",
    );
    process.exit(1);
  }
  console.log(`public/assets/tokens.css matches ${SOURCE}`);
} else {
  writeFileSync(OUTPUT, wanted);
  console.log(`wrote public/assets/tokens.css from ${SOURCE}`);
}
